### ISSUE TITLE
AttributeError: 'str' object has no attribute 'masked_select'

### ISSUE THREAD

**Issue by theartpiece** [ucinlp/autoprompt#49]
I am running the code on LAMA data (Fact-retreival dataset) and am facing following issue-
I ran this command--

```
python -m autoprompt.create_trigger    
      --train data/train.jsonl     
      --dev data/dev.jsonl
      --template '<s> {sub_label} [T] [T] [T] [P] . </s>'
      --num-cand 10     
      --accumulation-steps 1     
      --model-name roberta-large     
      --bsz 56     --eval-size 56     --iters 1000     
      --label-field 'obj_label'     
      --tokenize-labels     
      --filter     
      --print-lama

```

```
Traceback (most recent call last):
  File "/mnt/infonas/data/baekgupta/miniconda3/envs/tkgqa_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/infonas/data/baekgupta/miniconda3/envs/tkgqa_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/infonas/data/baekgupta/codlb/lm-kbc/autoprompt/autoprompt/create_trigger.py", line 529, in <module>
    run_model(args)
  File "/mnt/infonas/data/baekgupta/codlb/lm-kbc/autoprompt/autoprompt/create_trigger.py", line 295, in run_model
    predict_logits = predictor(model_inputs, trigger_ids)
  File "/mnt/infonas/data/baekgupta/codlb/lm-kbc/autoprompt/autoprompt/create_trigger.py", line 59, in __call__
    predict_logits = logits.masked_select(predict_mask.unsqueeze(-1)).view(logits.size(0), -1)
AttributeError: 'str' object has no attribute 'masked_select'
```

**Comment by taylorshin** [comment]
The command you gave works for me. Make sure your package versions match the ones in the requirements.txt file, especially the transformers library.

**Comment by aalkaswan** [comment]
As @taylorshin already pointed out this is caused by having a higher transformers version. If you still need to run a newer version of transformers to run newer models you can change the [line](https://github.com/ucinlp/autoprompt/blob/4fbae810b0f5289bcc1e4d856b2847bd33dac9f3/autoprompt/create_trigger.py#L52):

`logits, *_ = self._model(**model_inputs)`
to:
`logits = self._model(**model_inputs).logits` 

[Explained here](https://github.com/huggingface/transformers/issues/14194#issuecomment-953928763)
